language: cpp
sudo: required
stages:
    - name: deploy
      if: branch = master
    - name: before_script
      if: branch = master
matrix:
    include:
    - os: osx
      compiler: clang
      osx_image: xcode10.3
      script:
      - bash scripts/build.macos.release.sh
      - 'export VERSION=`cat src/version.h | grep " VERSION " | sed "s/.*\"v\(.*\)\"/\1/g"`'
      - mv subconverter_darwin64.tar.gz subconverter_$VERSION_darwin64.tar.gz
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        file: "subconverter_$VERSION_darwin64.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - services: docker
      script:
      - docker pull alpine:latest
      - docker run -v $TRAVIS_BUILD_DIR:/root/workdir alpine:latest /bin/sh -c "apk add bash git && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
      - 'export VERSION=`cat src/version.h | grep " VERSION " | sed "s/.*\"v\(.*\)\"/\1/g"`'
      - mv subconverter_linux64.tar.gz subconverter_$VERSION_linux64.tar.gz
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        file: "subconverter_$VERSION_linux64.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
